package com.car.entity.user;

import java.util.Date;

public class UserPushRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_push_rel.push_id
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    private Integer pushId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_push_rel.user_id
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_push_rel.datea
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    private Date datea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_push_rel.push_id
     *
     * @return the value of user_push_rel.push_id
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    public Integer getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_push_rel.push_id
     *
     * @param pushId the value for user_push_rel.push_id
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    public void setPushId(Integer pushId) {
        this.pushId = pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_push_rel.user_id
     *
     * @return the value of user_push_rel.user_id
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_push_rel.user_id
     *
     * @param userId the value for user_push_rel.user_id
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_push_rel.datea
     *
     * @return the value of user_push_rel.datea
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    public Date getDatea() {
        return datea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_push_rel.datea
     *
     * @param datea the value for user_push_rel.datea
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    public void setDatea(Date datea) {
        this.datea = datea;
    }
}