package com.car.mapper.user;

import com.car.entity.user.CarUserComment;

public interface CarUserCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_user_comment
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    int insert(CarUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_user_comment
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    int insertSelective(CarUserComment record);
}