package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.CycleImage;

public interface CycleImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_image
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_image
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    int insert(CycleImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_image
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    int insertSelective(CycleImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_image
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    CycleImage selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_image
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    int updateByPrimaryKeySelective(CycleImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_image
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    int updateByPrimaryKey(CycleImage record);

	/**
	 * @return
	 */
	List<CycleImage> getAllImgs();

	void rankimgOrder(CycleImage cycleImage);
}