package com.car.entity.rep;

public class CarRepRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_rep_rel.tra_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    private Integer traId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_rep_rel.car_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_rep_rel.rep_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    private Integer repId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_rep_rel.car_num
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    private Integer carNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_rep_rel.tra_id
     *
     * @return the value of car_rep_rel.tra_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public Integer getTraId() {
        return traId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_rep_rel.tra_id
     *
     * @param traId the value for car_rep_rel.tra_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public void setTraId(Integer traId) {
        this.traId = traId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_rep_rel.car_id
     *
     * @return the value of car_rep_rel.car_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_rep_rel.car_id
     *
     * @param carId the value for car_rep_rel.car_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_rep_rel.rep_id
     *
     * @return the value of car_rep_rel.rep_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public Integer getRepId() {
        return repId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_rep_rel.rep_id
     *
     * @param repId the value for car_rep_rel.rep_id
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public void setRepId(Integer repId) {
        this.repId = repId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_rep_rel.car_num
     *
     * @return the value of car_rep_rel.car_num
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public Integer getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_rep_rel.car_num
     *
     * @param carNum the value for car_rep_rel.car_num
     *
     * @mbggenerated Wed Apr 25 20:46:38 CST 2018
     */
    public void setCarNum(Integer carNum) {
        this.carNum = carNum;
    }
    private String carName;

	public String getCarName() {
		return carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}
    
}