package com.car.entity.rep;

public class Repository {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_repository.rep_id
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    private Integer repId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_repository.rep_name
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    private String repName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_repository.rep_stock
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    private Integer repStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_repository.dis_id
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    private Integer disId;
    
    private String disName;
    
    
    
    public String getDisName() {
		return disName;
	}

	public void setDisName(String disName) {
		this.disName = disName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_repository.rep_id
     *
     * @return the value of car_repository.rep_id
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public Integer getRepId() {
        return repId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_repository.rep_id
     *
     * @param repId the value for car_repository.rep_id
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public void setRepId(Integer repId) {
        this.repId = repId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_repository.rep_name
     *
     * @return the value of car_repository.rep_name
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public String getRepName() {
        return repName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_repository.rep_name
     *
     * @param repName the value for car_repository.rep_name
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public void setRepName(String repName) {
        this.repName = repName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_repository.rep_stock
     *
     * @return the value of car_repository.rep_stock
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public Integer getRepStock() {
        return repStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_repository.rep_stock
     *
     * @param repStock the value for car_repository.rep_stock
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public void setRepStock(Integer repStock) {
        this.repStock = repStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_repository.dis_id
     *
     * @return the value of car_repository.dis_id
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public Integer getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_repository.dis_id
     *
     * @param disId the value for car_repository.dis_id
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    public void setDisId(Integer disId) {
        this.disId = disId;
    }
}