package com.car.mapper.user;

import java.util.List;

import com.car.entity.car.CarGoods;
import com.car.entity.user.Browsinghistory;

public interface BrowsinghistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsinghistory
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    int insert(Browsinghistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsinghistory
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    int insertSelective(Browsinghistory record);

	/**
	 * @param browsinghistory
	 */
	List<Browsinghistory> findHisById(Browsinghistory browsinghistory);

	/**
	 * @param browsinghistory
	 */
	void update(Browsinghistory browsinghistory);

	/**
	 * @param userId
	 * @return
	 */
	List<Browsinghistory> getUserHisLookCars(Integer userId);

	/**
	 * @param userId
	 */
	void clearAll(Integer userId);
}