package com.car.mapper.user;

import java.util.List;

import com.car.entity.user.Coupon;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    int deleteByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    Coupon selectByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    int updateByPrimaryKey(Coupon record);
    
    List<Coupon> getCouponList();
    List<Coupon> getCouponUserList(Integer userId);
}