package com.car.mapper.user;

import java.util.List;

import com.car.entity.user.OrderForm;

public interface OrderFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated Sun Apr 15 14:40:08 CST 2018
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated Sun Apr 15 14:40:08 CST 2018
     */
    int insert(OrderForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated Sun Apr 15 14:40:08 CST 2018
     */
    int insertSelective(OrderForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated Sun Apr 15 14:40:08 CST 2018
     */
    OrderForm selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated Sun Apr 15 14:40:08 CST 2018
     */
    int updateByPrimaryKeySelective(OrderForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated Sun Apr 15 14:40:08 CST 2018
     */
    int updateByPrimaryKey(OrderForm record);

	List<OrderForm> getOrderFormList();

	void updateZF(OrderForm record);
}