package com.car.mapper.user;

import com.car.entity.user.UserPushRel;

public interface UserPushRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_push_rel
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    int insert(UserPushRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_push_rel
     *
     * @mbggenerated Sun Apr 15 14:38:37 CST 2018
     */
    int insertSelective(UserPushRel record);
}