package com.car.mapper.user;

import com.car.entity.user.UserCollect;

public interface UserCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 14:39:50 CST 2018
     */
    int insert(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 14:39:50 CST 2018
     */
    int insertSelective(UserCollect record);

	/**
	 * @param userCollect
	 */
	void del(UserCollect userCollect);
}