package com.car.mapper.user;

import java.util.List;

import com.car.entity.user.User;
import com.car.entity.user.UserApply;

public interface UserApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_apply
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    int deleteByPrimaryKey(Integer applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_apply
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    int insert(UserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_apply
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    int insertSelective(UserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_apply
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    UserApply selectByPrimaryKey(Integer applyId);
    
	UserApply getApplyByIds(Integer applyId);

	void updateLL(UserApply apply);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_apply
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    int updateByPrimaryKeySelective(UserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_apply
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    int updateByPrimaryKey(UserApply record);

	/**
	 * @return
	 */
	List<UserApply> getAllApplies();

	/**
	 * @param user
	 * @return
	 */
	List<UserApply> getApplyByUserId(User user);

	UserApply getApplyById(Integer applyId);
}