package com.car.entity.car;

public class CarModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.model_id
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.model_name
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    private String modelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.model_id
     *
     * @return the value of car_model.model_id
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.model_id
     *
     * @param modelId the value for car_model.model_id
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.model_name
     *
     * @return the value of car_model.model_name
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.model_name
     *
     * @param modelName the value for car_model.model_name
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
}