package com.car.entity.car;

public class CarBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.brand_id
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_brand.brand_name
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    private String brandName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.brand_id
     *
     * @return the value of car_brand.brand_id
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.brand_id
     *
     * @param brandId the value for car_brand.brand_id
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.brand_name
     *
     * @return the value of car_brand.brand_name
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.brand_name
     *
     * @param brandName the value for car_brand.brand_name
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
}