package com.car.entity.user;

import java.util.Date;

public class UserApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.apply_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private Integer applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.apply_content
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private String applyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.car_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.user_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.apply_time
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private String applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.ready_time
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private String readyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.apply_state
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private Integer applyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.apply_comment
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    private String applyComment;
    
    private String userName;
    private String carName;
    private String repName;

    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRepName() {
		return repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}

	public String getCarName() {
		return carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.apply_id
     *
     * @return the value of user_apply.apply_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.apply_id
     *
     * @param applyId the value for user_apply.apply_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.apply_content
     *
     * @return the value of user_apply.apply_content
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public String getApplyContent() {
        return applyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.apply_content
     *
     * @param applyContent the value for user_apply.apply_content
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.car_id
     *
     * @return the value of user_apply.car_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.car_id
     *
     * @param carId the value for user_apply.car_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.user_id
     *
     * @return the value of user_apply.user_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.user_id
     *
     * @param userId the value for user_apply.user_id
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.apply_time
     *
     * @return the value of user_apply.apply_time
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public String getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.apply_time
     *
     * @param applyTime the value for user_apply.apply_time
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setApplyTime(String applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.ready_time
     *
     * @return the value of user_apply.ready_time
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public String getReadyTime() {
        return readyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.ready_time
     *
     * @param readyTime the value for user_apply.ready_time
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setReadyTime(String readyTime) {
        this.readyTime = readyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.apply_state
     *
     * @return the value of user_apply.apply_state
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public Integer getApplyState() {
        return applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.apply_state
     *
     * @param applyState the value for user_apply.apply_state
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setApplyState(Integer applyState) {
        this.applyState = applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.apply_comment
     *
     * @return the value of user_apply.apply_comment
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public String getApplyComment() {
        return applyComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.apply_comment
     *
     * @param applyComment the value for user_apply.apply_comment
     *
     * @mbggenerated Sun Apr 15 14:41:53 CST 2018
     */
    public void setApplyComment(String applyComment) {
        this.applyComment = applyComment;
    }
}