package com.car.mapper.user;

import com.car.entity.user.UserCoupon;

public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_user_coupon_rel
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_user_coupon_rel
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    int insertSelective(UserCoupon record);
}