package com.car.mapper.manager;

import java.util.List;

import com.car.entity.manager.ManagerRole;

public interface ManagerRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    int insert(ManagerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    int insertSelective(ManagerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    ManagerRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    int updateByPrimaryKeySelective(ManagerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    int updateByPrimaryKey(ManagerRole record);

	List<ManagerRole> findManageRoleList();

	ManagerRole findmRollebyRoleId(Integer roleId);

}