package com.car.mapper.manager;

import java.util.HashMap;
import java.util.List;

import com.car.entity.manager.ManageUser;


public interface ManageUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table manage_user
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	int deleteByPrimaryKey(Integer manageId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table manage_user
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	int insert(ManageUser record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table manage_user
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	int insertSelective(ManageUser record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table manage_user
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	ManageUser selectByPrimaryKey(Integer manageId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table manage_user
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	int updateByPrimaryKeySelective(ManageUser record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table manage_user
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	int updateByPrimaryKey(ManageUser record);


	//ht
	List<ManageUser> findManageUserList();


    //ht
	int updateLoginPwdInit(ManageUser manageUser);
    //ht
	List<ManageUser> finduserbyrid(Integer roleId);

	Integer insertt(ManageUser mu);

	ManageUser login(ManageUser mu);
    //ht
	int stopManageUser(Integer manageId);

	void enableManageUser(int parseInt);

	ManageUser getUserByUsername(String loginName);

	void updateNumByManageId(Integer manageId);


	void updateDateTimeSelectiveByUid(ManageUser userCopy);


	void updateLoginNumByUid(ManageUser userCopy);

	


	

	
}