package com.car.entity.user;

public class AfterSale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.sale_id
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    private Integer saleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.sale_name
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    private String saleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.sale_money
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    private Double saleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.sale_content
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    private String saleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.sale_id
     *
     * @return the value of after_sale.sale_id
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public Integer getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.sale_id
     *
     * @param saleId the value for after_sale.sale_id
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.sale_name
     *
     * @return the value of after_sale.sale_name
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public String getSaleName() {
        return saleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.sale_name
     *
     * @param saleName the value for after_sale.sale_name
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public void setSaleName(String saleName) {
        this.saleName = saleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.sale_money
     *
     * @return the value of after_sale.sale_money
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public Double getSaleMoney() {
        return saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.sale_money
     *
     * @param saleMoney the value for after_sale.sale_money
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public void setSaleMoney(Double saleMoney) {
        this.saleMoney = saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.sale_content
     *
     * @return the value of after_sale.sale_content
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public String getSaleContent() {
        return saleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.sale_content
     *
     * @param saleContent the value for after_sale.sale_content
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    public void setSaleContent(String saleContent) {
        this.saleContent = saleContent;
    }
}