package com.car.entity.user;

import java.util.Date;

public class Browsinghistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsinghistory.user_id
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsinghistory.car_id
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsinghistory.bro_time
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    private String broTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsinghistory.user_id
     *
     * @return the value of browsinghistory.user_id
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsinghistory.user_id
     *
     * @param userId the value for browsinghistory.user_id
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsinghistory.car_id
     *
     * @return the value of browsinghistory.car_id
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsinghistory.car_id
     *
     * @param carId the value for browsinghistory.car_id
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsinghistory.bro_time
     *
     * @return the value of browsinghistory.bro_time
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    public String getBroTime() {
        return broTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsinghistory.bro_time
     *
     * @param broTime the value for browsinghistory.bro_time
     *
     * @mbggenerated Sun Apr 15 14:41:33 CST 2018
     */
    public void setBroTime(String broTime) {
        this.broTime = broTime;
    }
}