package com.car.entity.user;

public class CarUserComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_user_comment.user_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_user_comment.car_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_user_comment.comment_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    private Integer commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_user_comment.user_id
     *
     * @return the value of car_user_comment.user_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_user_comment.user_id
     *
     * @param userId the value for car_user_comment.user_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_user_comment.car_id
     *
     * @return the value of car_user_comment.car_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_user_comment.car_id
     *
     * @param carId the value for car_user_comment.car_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_user_comment.comment_id
     *
     * @return the value of car_user_comment.comment_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_user_comment.comment_id
     *
     * @param commentId the value for car_user_comment.comment_id
     *
     * @mbggenerated Sun Apr 15 14:38:20 CST 2018
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
}