package com.car.entity.user;

public class UserLevelRel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user_level.user_id
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user_level.level_id
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	private Integer levelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user_level.level_num
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	private Integer levelNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user_level.user_id
	 * @return  the value of buyer_user_level.user_id
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user_level.user_id
	 * @param userId  the value for buyer_user_level.user_id
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user_level.level_id
	 * @return  the value of buyer_user_level.level_id
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	public Integer getLevelId() {
		return levelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user_level.level_id
	 * @param levelId  the value for buyer_user_level.level_id
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user_level.level_num
	 * @return  the value of buyer_user_level.level_num
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	public Integer getLevelNum() {
		return levelNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user_level.level_num
	 * @param levelNum  the value for buyer_user_level.level_num
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	public void setLevelNum(Integer levelNum) {
		this.levelNum = levelNum;
	}
}