package com.car.mapper.user;

import com.car.entity.user.UserLevelRel;

public interface UserLevelRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user_level
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	int insert(UserLevelRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user_level
	 * @mbggenerated  Wed Apr 18 21:42:06 CST 2018
	 */
	int insertSelective(UserLevelRel record);
}