package com.car.entity.user;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_id
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_name
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    private String couponName;
    private String realName;
    private String userName;
    
    

    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_money
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    private Double couponMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_content
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    private String couponContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_usedeadline
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    private String couponUsedeadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_id
     *
     * @return the value of coupon.coupon_id
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_id
     *
     * @param couponId the value for coupon.coupon_id
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_name
     *
     * @return the value of coupon.coupon_name
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_name
     *
     * @param couponName the value for coupon.coupon_name
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_money
     *
     * @return the value of coupon.coupon_money
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public Double getCouponMoney() {
        return couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_money
     *
     * @param couponMoney the value for coupon.coupon_money
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public void setCouponMoney(Double couponMoney) {
        this.couponMoney = couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_content
     *
     * @return the value of coupon.coupon_content
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public String getCouponContent() {
        return couponContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_content
     *
     * @param couponContent the value for coupon.coupon_content
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public void setCouponContent(String couponContent) {
        this.couponContent = couponContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_usedeadline
     *
     * @return the value of coupon.coupon_usedeadline
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public String getCouponUsedeadline() {
        return couponUsedeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_usedeadline
     *
     * @param couponUsedeadline the value for coupon.coupon_usedeadline
     *
     * @mbggenerated Sun Apr 15 14:38:54 CST 2018
     */
    public void setCouponUsedeadline(String couponUsedeadline) {
        this.couponUsedeadline = couponUsedeadline;
    }
}