package com.car.entity.car;

public class Producer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_producer.pro_id
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_producer.pro_name
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_producer.people_name
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    private String peopleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_producer.people_tel
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    private String peopleTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_producer.pro_address
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    private String proAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_producer.pro_id
     *
     * @return the value of rep_producer.pro_id
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_producer.pro_id
     *
     * @param proId the value for rep_producer.pro_id
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_producer.pro_name
     *
     * @return the value of rep_producer.pro_name
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_producer.pro_name
     *
     * @param proName the value for rep_producer.pro_name
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_producer.people_name
     *
     * @return the value of rep_producer.people_name
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public String getPeopleName() {
        return peopleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_producer.people_name
     *
     * @param peopleName the value for rep_producer.people_name
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public void setPeopleName(String peopleName) {
        this.peopleName = peopleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_producer.people_tel
     *
     * @return the value of rep_producer.people_tel
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public String getPeopleTel() {
        return peopleTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_producer.people_tel
     *
     * @param peopleTel the value for rep_producer.people_tel
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public void setPeopleTel(String peopleTel) {
        this.peopleTel = peopleTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_producer.pro_address
     *
     * @return the value of rep_producer.pro_address
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public String getProAddress() {
        return proAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_producer.pro_address
     *
     * @param proAddress the value for rep_producer.pro_address
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    public void setProAddress(String proAddress) {
        this.proAddress = proAddress;
    }
}