package com.car.entity.manager;

import java.util.List;

public class ManagerRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.role_id
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.role_name
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.role_content
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    private String roleContent;

    private List<ManageUser> muList;
    private List<ManagerResources> mresList;
    
    public List<ManageUser> getMuList() {
		return muList;
	}

	public void setMuList(List<ManageUser> muList) {
		this.muList = muList;
	}

	public List<ManagerResources> getMresList() {
		return mresList;
	}

	public void setMresList(List<ManagerResources> mresList) {
		this.mresList = mresList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.role_id
     *
     * @return the value of manage_role.role_id
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.role_id
     *
     * @param roleId the value for manage_role.role_id
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.role_name
     *
     * @return the value of manage_role.role_name
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.role_name
     *
     * @param roleName the value for manage_role.role_name
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.role_content
     *
     * @return the value of manage_role.role_content
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    public String getRoleContent() {
        return roleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.role_content
     *
     * @param roleContent the value for manage_role.role_content
     *
     * @mbggenerated Sun Apr 15 14:35:16 CST 2018
     */
    public void setRoleContent(String roleContent) {
        this.roleContent = roleContent;
    }
}