package com.car.mapper.user;

import java.util.List;

import com.car.entity.user.BuyerLevel;
import com.car.entity.user.User;

public interface UserMapper {
    

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_user
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	int updateByPrimaryKey(User record);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_user
     *
     * @mbggenerated Sun Apr 15 14:37:33 CST 2018
     */
    

    User getUserByUsername(String userName);

	void updateNumByUid(Integer userId);

	void updateDateTimeSelectiveByUid(User userCopy);

	void updateLoginNumByUid(User userCopy);

	/**
	 * @return
	 */
	List<User> getAllUserList();
	
	List<User> getAllUserLists(Integer userId);

	User loginn(User user);

	int blockUser(Integer userId);

	User selectUser(User user);

	

	User selectPwd(User user);

	void updatePwd(User user);


	void updateByUser(User user);


	/**
	 * @param user
	 * @return
	 */
	User selSameUser(User user);

}