package com.car.entity.user;


public class UserComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.comment_id
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.comment_content
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.comment_time
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    private String commentTime;
    private String carName;
    private int carId;
    private String userName;
    private Integer userId;
    private String userImg;
    private String levelName;
    private String levelImg;
    public String getCarName() {
		return carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	public int getCarId() {
		return carId;
	}

	public void setCarId(int carId) {
		this.carId = carId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.comment_id
     *
     * @return the value of user_comment.comment_id
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.comment_id
     *
     * @param commentId the value for user_comment.comment_id
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.comment_content
     *
     * @return the value of user_comment.comment_content
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.comment_content
     *
     * @param commentContent the value for user_comment.comment_content
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.comment_time
     *
     * @return the value of user_comment.comment_time
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    public String getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.comment_time
     *
     * @param commentTime the value for user_comment.comment_time
     *
     * @mbggenerated Sun Apr 15 14:37:56 CST 2018
     */
    public void setCommentTime(String commentTime) {
        this.commentTime = commentTime;
    }


	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserImg() {
		return userImg;
	}

	public void setUserImg(String userImg) {
		this.userImg = userImg;
	}

	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public String getLevelImg() {
		return levelImg;
	}

	public void setLevelImg(String levelImg) {
		this.levelImg = levelImg;
	}
    
}