package com.car.entity.user;

public class UserCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_user_coupon_rel.user_id
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_user_coupon_rel.coupon_id
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    private Integer couponId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_user_coupon_rel.user_id
     *
     * @return the value of buyer_user_coupon_rel.user_id
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_user_coupon_rel.user_id
     *
     * @param userId the value for buyer_user_coupon_rel.user_id
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_user_coupon_rel.coupon_id
     *
     * @return the value of buyer_user_coupon_rel.coupon_id
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_user_coupon_rel.coupon_id
     *
     * @param couponId the value for buyer_user_coupon_rel.coupon_id
     *
     * @mbggenerated Sun Apr 15 14:39:24 CST 2018
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }
}