package com.car.entity.manager;

public class ManagerFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_function.fun_id
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    private Integer funId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_function.fun_name
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    private String funName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_function.fun_content
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    private String funContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_function.fun_id
     *
     * @return the value of manage_function.fun_id
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    public Integer getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_function.fun_id
     *
     * @param funId the value for manage_function.fun_id
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    public void setFunId(Integer funId) {
        this.funId = funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_function.fun_name
     *
     * @return the value of manage_function.fun_name
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    public String getFunName() {
        return funName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_function.fun_name
     *
     * @param funName the value for manage_function.fun_name
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    public void setFunName(String funName) {
        this.funName = funName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_function.fun_content
     *
     * @return the value of manage_function.fun_content
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    public String getFunContent() {
        return funContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_function.fun_content
     *
     * @param funContent the value for manage_function.fun_content
     *
     * @mbggenerated Sun Apr 15 14:34:18 CST 2018
     */
    public void setFunContent(String funContent) {
        this.funContent = funContent;
    }
}