package com.car.entity.manager;

import java.util.Date;

public class ManageUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_id
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private Integer manageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.login_name
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.login_pwd
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String loginPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_name
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String manageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_sex
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private Integer manageSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_idcard
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String manageIdcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_emails
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String manageEmails;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_tel
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String manageTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_img
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String manageImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_status
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private Integer manageStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.manage_birthday
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String manageBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.login_lasttime
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private Date loginLasttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.login_num
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private Integer loginNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.create_time
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column manage_user.login_time
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	private String loginTime;




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_id
	 * @return  the value of manage_user.manage_id
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public Integer getManageId() {
		return manageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_id
	 * @param manageId  the value for manage_user.manage_id
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageId(Integer manageId) {
		this.manageId = manageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.login_name
	 * @return  the value of manage_user.login_name
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.login_name
	 * @param loginName  the value for manage_user.login_name
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.login_pwd
	 * @return  the value of manage_user.login_pwd
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getLoginPwd() {
		return loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.login_pwd
	 * @param loginPwd  the value for manage_user.login_pwd
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_name
	 * @return  the value of manage_user.manage_name
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getManageName() {
		return manageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_name
	 * @param manageName  the value for manage_user.manage_name
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageName(String manageName) {
		this.manageName = manageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_sex
	 * @return  the value of manage_user.manage_sex
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public Integer getManageSex() {
		return manageSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_sex
	 * @param manageSex  the value for manage_user.manage_sex
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageSex(Integer manageSex) {
		this.manageSex = manageSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_idcard
	 * @return  the value of manage_user.manage_idcard
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getManageIdcard() {
		return manageIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_idcard
	 * @param manageIdcard  the value for manage_user.manage_idcard
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageIdcard(String manageIdcard) {
		this.manageIdcard = manageIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_emails
	 * @return  the value of manage_user.manage_emails
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getManageEmails() {
		return manageEmails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_emails
	 * @param manageEmails  the value for manage_user.manage_emails
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageEmails(String manageEmails) {
		this.manageEmails = manageEmails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_tel
	 * @return  the value of manage_user.manage_tel
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getManageTel() {
		return manageTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_tel
	 * @param manageTel  the value for manage_user.manage_tel
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageTel(String manageTel) {
		this.manageTel = manageTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_img
	 * @return  the value of manage_user.manage_img
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getManageImg() {
		return manageImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_img
	 * @param manageImg  the value for manage_user.manage_img
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageImg(String manageImg) {
		this.manageImg = manageImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_status
	 * @return  the value of manage_user.manage_status
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public Integer getManageStatus() {
		return manageStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_status
	 * @param manageStatus  the value for manage_user.manage_status
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageStatus(Integer manageStatus) {
		this.manageStatus = manageStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.manage_birthday
	 * @return  the value of manage_user.manage_birthday
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getManageBirthday() {
		return manageBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.manage_birthday
	 * @param manageBirthday  the value for manage_user.manage_birthday
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setManageBirthday(String manageBirthday) {
		this.manageBirthday = manageBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.login_lasttime
	 * @return  the value of manage_user.login_lasttime
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public Date getLoginLasttime() {
		return loginLasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.login_lasttime
	 * @param loginLasttime  the value for manage_user.login_lasttime
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setLoginLasttime(Date loginLasttime) {
		this.loginLasttime = loginLasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.login_num
	 * @return  the value of manage_user.login_num
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public Integer getLoginNum() {
		return loginNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.login_num
	 * @param loginNum  the value for manage_user.login_num
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setLoginNum(Integer loginNum) {
		this.loginNum = loginNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.create_time
	 * @return  the value of manage_user.create_time
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.create_time
	 * @param createTime  the value for manage_user.create_time
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column manage_user.login_time
	 * @return  the value of manage_user.login_time
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public String getLoginTime() {
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column manage_user.login_time
	 * @param loginTime  the value for manage_user.login_time
	 * @mbggenerated  Thu Apr 26 21:27:51 CST 2018
	 */
	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}

	private Integer roleId;
	private String roleName;
	
	
	
	
	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}