package com.car.entity.manager;

public class RoleResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_resources.role_id
     *
     * @mbggenerated Sun Apr 15 14:36:16 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_resources.res_id
     *
     * @mbggenerated Sun Apr 15 14:36:16 CST 2018
     */
    private Integer resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_resources.role_id
     *
     * @return the value of manage_role_resources.role_id
     *
     * @mbggenerated Sun Apr 15 14:36:16 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_resources.role_id
     *
     * @param roleId the value for manage_role_resources.role_id
     *
     * @mbggenerated Sun Apr 15 14:36:16 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_resources.res_id
     *
     * @return the value of manage_role_resources.res_id
     *
     * @mbggenerated Sun Apr 15 14:36:16 CST 2018
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_resources.res_id
     *
     * @param resId the value for manage_role_resources.res_id
     *
     * @mbggenerated Sun Apr 15 14:36:16 CST 2018
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }
}