package com.car.entity.manager;

public class ManagerResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_resources.res_id
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    private Integer resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_resources.res_name
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_resources.res_url
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_resources.res_content
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    private String resContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_resources.pid
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_resources.res_order
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    private Integer resOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_resources.res_id
     *
     * @return the value of manage_resources.res_id
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_resources.res_id
     *
     * @param resId the value for manage_resources.res_id
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_resources.res_name
     *
     * @return the value of manage_resources.res_name
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_resources.res_name
     *
     * @param resName the value for manage_resources.res_name
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public void setResName(String resName) {
        this.resName = resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_resources.res_url
     *
     * @return the value of manage_resources.res_url
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_resources.res_url
     *
     * @param resUrl the value for manage_resources.res_url
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_resources.res_content
     *
     * @return the value of manage_resources.res_content
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public String getResContent() {
        return resContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_resources.res_content
     *
     * @param resContent the value for manage_resources.res_content
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public void setResContent(String resContent) {
        this.resContent = resContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_resources.pid
     *
     * @return the value of manage_resources.pid
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_resources.pid
     *
     * @param pid the value for manage_resources.pid
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_resources.res_order
     *
     * @return the value of manage_resources.res_order
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public Integer getResOrder() {
        return resOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_resources.res_order
     *
     * @param resOrder the value for manage_resources.res_order
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    public void setResOrder(Integer resOrder) {
        this.resOrder = resOrder;
    }
}