package com.car.entity.manager;

import java.util.Date;

public class Push {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.push_id
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    private Integer pushId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.push_name
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    private String pushName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.push_content
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    private String pushContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.push_date
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    private String pushDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.push_id
     *
     * @return the value of push.push_id
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public Integer getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.push_id
     *
     * @param pushId the value for push.push_id
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public void setPushId(Integer pushId) {
        this.pushId = pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.push_name
     *
     * @return the value of push.push_name
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public String getPushName() {
        return pushName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.push_name
     *
     * @param pushName the value for push.push_name
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public void setPushName(String pushName) {
        this.pushName = pushName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.push_content
     *
     * @return the value of push.push_content
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public String getPushContent() {
        return pushContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.push_content
     *
     * @param pushContent the value for push.push_content
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public void setPushContent(String pushContent) {
        this.pushContent = pushContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.push_date
     *
     * @return the value of push.push_date
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public String getPushDate() {
        return pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.push_date
     *
     * @param pushDate the value for push.push_date
     *
     * @mbggenerated Sun Apr 15 14:36:49 CST 2018
     */
    public void setPushDate(String pushDate) {
        this.pushDate = pushDate;
    }
}