package com.car.mapper.user;

import com.car.entity.user.AfterSale;

public interface AfterSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    int deleteByPrimaryKey(Integer saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    int insert(AfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    int insertSelective(AfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    AfterSale selectByPrimaryKey(Integer saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    int updateByPrimaryKeySelective(AfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Sun Apr 15 14:42:06 CST 2018
     */
    int updateByPrimaryKey(AfterSale record);
}