package com.car.entity.manager;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role.manage_id
     *
     * @mbggenerated Sun Apr 15 14:36:36 CST 2018
     */
    private Integer manageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role.role_id
     *
     * @mbggenerated Sun Apr 15 14:36:36 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role.manage_id
     *
     * @return the value of manage_user_role.manage_id
     *
     * @mbggenerated Sun Apr 15 14:36:36 CST 2018
     */
    public Integer getManageId() {
        return manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role.manage_id
     *
     * @param manageId the value for manage_user_role.manage_id
     *
     * @mbggenerated Sun Apr 15 14:36:36 CST 2018
     */
    public void setManageId(Integer manageId) {
        this.manageId = manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role.role_id
     *
     * @return the value of manage_user_role.role_id
     *
     * @mbggenerated Sun Apr 15 14:36:36 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role.role_id
     *
     * @param roleId the value for manage_user_role.role_id
     *
     * @mbggenerated Sun Apr 15 14:36:36 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}