package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.CarBrandModel;

public interface CarBrandModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_brand_model_rel
	 * @mbggenerated  Wed Apr 18 08:28:40 CST 2018
	 */
	int deleteByPrimaryKey(Integer carId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_brand_model_rel
	 * @mbggenerated  Wed Apr 18 08:28:40 CST 2018
	 */
	int insert(CarBrandModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_brand_model_rel
	 * @mbggenerated  Wed Apr 18 08:28:40 CST 2018
	 */
	int insertSelective(CarBrandModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_brand_model_rel
	 * @mbggenerated  Wed Apr 18 08:28:40 CST 2018
	 */
	CarBrandModel selectByPrimaryKey(Integer carId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_brand_model_rel
	 * @mbggenerated  Wed Apr 18 08:28:40 CST 2018
	 */
	int updateByPrimaryKeySelective(CarBrandModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_brand_model_rel
	 * @mbggenerated  Wed Apr 18 08:28:40 CST 2018
	 */
	int updateByPrimaryKey(CarBrandModel record);

	List<CarBrandModel> findOtherList(Integer carId);

	CarBrandModel findMessage(CarBrandModel cbm);

	CarBrandModel findcbmMessage(Integer carId);

	void updateByProId(Integer proId);

	void updateBrandByBrandId(Integer brandId);

	void updateModelByModelId(Integer modelId);


	
}