package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.CarColor;

public interface CarColorMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_color
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	int deleteByPrimaryKey(Integer colorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_color
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	int insert(CarColor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_color
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	int insertSelective(CarColor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_color
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	CarColor selectByPrimaryKey(Integer colorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_color
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	int updateByPrimaryKeySelective(CarColor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_color
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	int updateByPrimaryKey(CarColor record);

	List<CarColor> findColorList();

	List<CarColor> getColorList(CarColor color);

}