package com.car.mapper.car;

import java.util.HashMap;
import java.util.List;

import com.car.entity.car.CarGoods;
import com.car.entity.user.User;

public interface CarGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_goods
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    int deleteByPrimaryKey(Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_goods
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    int insert(CarGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_goods
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    int insertSelective(CarGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_goods
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    CarGoods selectByPrimaryKey(Integer carId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_goods
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    int updateByPrimaryKeySelective(CarGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_goods
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    int updateByPrimaryKey(CarGoods record);
    /**
     * 
     * @return
     */
	List<CarGoods> findcarList();
	/**
	 * 总数量
	 * @param goods
	 * @return
	 */
	public Integer getCount(CarGoods goods);
	/**
	 * @param hashMap 
	 * @return
	 */
	public List<CarGoods> getGoodsList(HashMap<Object, Object> hashMap);
	/**
	 * 
	 * @param bid
	 * @param mid
	 * @param pid
	 * @return num
	 */
	public Integer getGoodsNum(HashMap<Object, Object> hashMap);
	/**
	 * @param hashMap
	 * @return
	 */
	List<CarGoods> getGoodsBuyIds(HashMap<Object, Object> hashMap);

	void mainCarImgUpdate(CarGoods carGoods);

	/**
	 * 单纯的列表
	 * @return
	 */
	List<CarGoods> getGoodsLists();
	
	List<CarGoods> getGoodsLists(String disId);

	List<CarGoods> findCarId();

	CarGoods selectCarNameByCarId(Integer carId);
	
	List<CarGoods> getGoods(String disId);

	CarGoods findCarByCarId(Integer carId);

	List<CarGoods> selectCollect(User user);

	/**
	 * @param parseInt
	 */
	void insertCollect(int carId);

	/**
	 * @param parseInt
	 */
	void delCollect(int carId);

	/**
	 * @param ids
	 * @return
	 */
	List<CarGoods> getCarsByIds(String ids);

	/**
	 * @param carGoods
	 */
	void insertAll(List<Object> carGoods);
}