package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.CarImg;

public interface CarImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_img
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_img
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    int insert(CarImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_img
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    int insertSelective(CarImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_img
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    CarImg selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_img
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    int updateByPrimaryKeySelective(CarImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_img
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    int updateByPrimaryKey(CarImg record);

	List<CarImg> toCarImgList(Integer carId);
}