package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.Producer;

public interface ProducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_producer
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    int deleteByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_producer
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    int insert(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_producer
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    int insertSelective(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_producer
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    Producer selectByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_producer
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    int updateByPrimaryKeySelective(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_producer
     *
     * @mbggenerated Sun Apr 15 14:26:38 CST 2018
     */
    int updateByPrimaryKey(Producer record);

	List<Producer> findProducerList();
}