package com.car.mapper.car;


import java.util.List;

import com.car.entity.car.CarBrand;


public interface CarBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    int insert(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    int insertSelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    CarBrand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    int updateByPrimaryKeySelective(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated Sun Apr 15 14:23:42 CST 2018
     */
    int updateByPrimaryKey(CarBrand record);
    
    
    

	List<CarBrand> getBrandList(CarBrand carBrand);

	List<CarBrand> findBrandList();
    
    
    
}