package com.car.entity.car;


public class CarGoodsPOI {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_name
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private String carName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_price
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_oilwear
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private String carOilwear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.configuration
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer configuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_cc
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Double carCc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_speed
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_status
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_safety
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carSafety;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_datea
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private String carDatea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_warranty
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carWarranty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_heat
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carHeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_col_num
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private Integer carColNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_goods.car_img
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    private String carImg;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_name
     *
     * @return the value of car_goods.car_name
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_name
     *
     * @param carName the value for car_goods.car_name
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarName(String carName) {
        this.carName = carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_price
     *
     * @return the value of car_goods.car_price
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_price
     *
     * @param carPrice the value for car_goods.car_price
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarPrice(Integer carPrice) {
        this.carPrice = carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_oilwear
     *
     * @return the value of car_goods.car_oilwear
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public String getCarOilwear() {
        return carOilwear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_oilwear
     *
     * @param carOilwear the value for car_goods.car_oilwear
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarOilwear(String carOilwear) {
        this.carOilwear = carOilwear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.configuration
     *
     * @return the value of car_goods.configuration
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getConfiguration() {
        return configuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.configuration
     *
     * @param configuration the value for car_goods.configuration
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setConfiguration(Integer configuration) {
        this.configuration = configuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_cc
     *
     * @return the value of car_goods.car_cc
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Double getCarCc() {
        return carCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_cc
     *
     * @param carCc the value for car_goods.car_cc
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarCc(Double carCc) {
        this.carCc = carCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_speed
     *
     * @return the value of car_goods.car_speed
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarSpeed() {
        return carSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_speed
     *
     * @param carSpeed the value for car_goods.car_speed
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarSpeed(Integer carSpeed) {
        this.carSpeed = carSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_status
     *
     * @return the value of car_goods.car_status
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarStatus() {
        return carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_status
     *
     * @param carStatus the value for car_goods.car_status
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarStatus(Integer carStatus) {
        this.carStatus = carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_safety
     *
     * @return the value of car_goods.car_safety
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarSafety() {
        return carSafety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_safety
     *
     * @param carSafety the value for car_goods.car_safety
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarSafety(Integer carSafety) {
        this.carSafety = carSafety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_datea
     *
     * @return the value of car_goods.car_datea
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public String getCarDatea() {
        return carDatea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_datea
     *
     * @param carDatea the value for car_goods.car_datea
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarDatea(String carDatea) {
        this.carDatea = carDatea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_warranty
     *
     * @return the value of car_goods.car_warranty
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarWarranty() {
        return carWarranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_warranty
     *
     * @param carWarranty the value for car_goods.car_warranty
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarWarranty(Integer carWarranty) {
        this.carWarranty = carWarranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_heat
     *
     * @return the value of car_goods.car_heat
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarHeat() {
        return carHeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_heat
     *
     * @param carHeat the value for car_goods.car_heat
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarHeat(Integer carHeat) {
        this.carHeat = carHeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_col_num
     *
     * @return the value of car_goods.car_col_num
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public Integer getCarColNum() {
        return carColNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_col_num
     *
     * @param carColNum the value for car_goods.car_col_num
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarColNum(Integer carColNum) {
        this.carColNum = carColNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_goods.car_img
     *
     * @return the value of car_goods.car_img
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public String getCarImg() {
        return carImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_goods.car_img
     *
     * @param carImg the value for car_goods.car_img
     *
     * @mbggenerated Sun Apr 15 14:20:53 CST 2018
     */
    public void setCarImg(String carImg) {
        this.carImg = carImg;
    }

    
    
   
    
    
}