package com.car.entity.car;

public class CarImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_img.img_id
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_img.img_address
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    private String imgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_img.img_order
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    private Integer imgOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_img.img_id
     *
     * @return the value of car_img.img_id
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_img.img_id
     *
     * @param imgId the value for car_img.img_id
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_img.img_address
     *
     * @return the value of car_img.img_address
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    public String getImgAddress() {
        return imgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_img.img_address
     *
     * @param imgAddress the value for car_img.img_address
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_img.img_order
     *
     * @return the value of car_img.img_order
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    public Integer getImgOrder() {
        return imgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_img.img_order
     *
     * @param imgOrder the value for car_img.img_order
     *
     * @mbggenerated Sun Apr 15 14:23:56 CST 2018
     */
    public void setImgOrder(Integer imgOrder) {
        this.imgOrder = imgOrder;
    }
}