package com.car.entity.car;

public class CycleImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycle_image.img_id
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycle_image.img_name
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycle_image.img_address
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    private String imgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycle_image.img_type
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    private Integer imgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycle_image.img_order
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    private Integer imgOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycle_image.car_id
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    private Integer carId;
    
    private String carName;
    
    
    public String getCarName() {
		return carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycle_image.img_id
     *
     * @return the value of cycle_image.img_id
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycle_image.img_id
     *
     * @param imgId the value for cycle_image.img_id
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycle_image.img_name
     *
     * @return the value of cycle_image.img_name
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycle_image.img_name
     *
     * @param imgName the value for cycle_image.img_name
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycle_image.img_address
     *
     * @return the value of cycle_image.img_address
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public String getImgAddress() {
        return imgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycle_image.img_address
     *
     * @param imgAddress the value for cycle_image.img_address
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycle_image.img_type
     *
     * @return the value of cycle_image.img_type
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public Integer getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycle_image.img_type
     *
     * @param imgType the value for cycle_image.img_type
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public void setImgType(Integer imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycle_image.img_order
     *
     * @return the value of cycle_image.img_order
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public Integer getImgOrder() {
        return imgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycle_image.img_order
     *
     * @param imgOrder the value for cycle_image.img_order
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public void setImgOrder(Integer imgOrder) {
        this.imgOrder = imgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycle_image.car_id
     *
     * @return the value of cycle_image.car_id
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycle_image.car_id
     *
     * @param carId the value for cycle_image.car_id
     *
     * @mbggenerated Sun Apr 15 14:22:25 CST 2018
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
}