package com.car.entity.rep;

public class RepDistrict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_district.dis_id
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    private Integer disId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_district.dis_name
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    private String disName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_district.p_id
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_district.dis_order
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    private Integer disOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_district.dis_id
     *
     * @return the value of rep_district.dis_id
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public Integer getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_district.dis_id
     *
     * @param disId the value for rep_district.dis_id
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public void setDisId(Integer disId) {
        this.disId = disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_district.dis_name
     *
     * @return the value of rep_district.dis_name
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public String getDisName() {
        return disName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_district.dis_name
     *
     * @param disName the value for rep_district.dis_name
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public void setDisName(String disName) {
        this.disName = disName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_district.p_id
     *
     * @return the value of rep_district.p_id
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_district.p_id
     *
     * @param pId the value for rep_district.p_id
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_district.dis_order
     *
     * @return the value of rep_district.dis_order
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public Integer getDisOrder() {
        return disOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_district.dis_order
     *
     * @param disOrder the value for rep_district.dis_order
     *
     * @mbggenerated Sun Apr 15 14:32:07 CST 2018
     */
    public void setDisOrder(Integer disOrder) {
        this.disOrder = disOrder;
    }
}