package com.car.entity.extra;

public class Navigationbar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigationbar.nav_id
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    private Integer navId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigationbar.nav_name
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    private String navName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigationbar.nav_address
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    private String navAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigationbar.fu_id
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    private Integer fuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigationbar.nav_order
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    private Integer navOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigationbar.nav_id
     *
     * @return the value of navigationbar.nav_id
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public Integer getNavId() {
        return navId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigationbar.nav_id
     *
     * @param navId the value for navigationbar.nav_id
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public void setNavId(Integer navId) {
        this.navId = navId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigationbar.nav_name
     *
     * @return the value of navigationbar.nav_name
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public String getNavName() {
        return navName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigationbar.nav_name
     *
     * @param navName the value for navigationbar.nav_name
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public void setNavName(String navName) {
        this.navName = navName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigationbar.nav_address
     *
     * @return the value of navigationbar.nav_address
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public String getNavAddress() {
        return navAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigationbar.nav_address
     *
     * @param navAddress the value for navigationbar.nav_address
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public void setNavAddress(String navAddress) {
        this.navAddress = navAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigationbar.fu_id
     *
     * @return the value of navigationbar.fu_id
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public Integer getFuId() {
        return fuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigationbar.fu_id
     *
     * @param fuId the value for navigationbar.fu_id
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public void setFuId(Integer fuId) {
        this.fuId = fuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigationbar.nav_order
     *
     * @return the value of navigationbar.nav_order
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public Integer getNavOrder() {
        return navOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigationbar.nav_order
     *
     * @param navOrder the value for navigationbar.nav_order
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    public void setNavOrder(Integer navOrder) {
        this.navOrder = navOrder;
    }
}