package com.car.mapper.manager;

import com.car.entity.manager.ResFunRel;

public interface ResFunRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_function_rel
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    int insert(ResFunRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_function_rel
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    int insertSelective(ResFunRel record);
}