package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.CarModel;

public interface CarModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    int insert(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    int insertSelective(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    CarModel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    int updateByPrimaryKeySelective(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated Sun Apr 15 14:22:41 CST 2018
     */
    int updateByPrimaryKey(CarModel record);
    
    
    
    List<CarModel> getModelList(CarModel model);
    

	List<CarModel> findModelList();

}