package com.car.entity.car;

public class CarColor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_color.color_id
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	private Integer colorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_color.color_name
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	private String colorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_color.color_rgb
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	private String colorRgb;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_color.color_id
	 * @return  the value of car_color.color_id
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	public Integer getColorId() {
		return colorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_color.color_id
	 * @param colorId  the value for car_color.color_id
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_color.color_name
	 * @return  the value of car_color.color_name
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	public String getColorName() {
		return colorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_color.color_name
	 * @param colorName  the value for car_color.color_name
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_color.color_rgb
	 * @return  the value of car_color.color_rgb
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	public String getColorRgb() {
		return colorRgb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_color.color_rgb
	 * @param colorRgb  the value for car_color.color_rgb
	 * @mbggenerated  Sat Apr 21 11:55:08 CST 2018
	 */
	public void setColorRgb(String colorRgb) {
		this.colorRgb = colorRgb;
	}
}