package com.car.entity.car;

public class CarColorRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_color_rel.goods_id
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_color_rel.color_id
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    private Integer colorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_color_rel.goods_id
     *
     * @return the value of car_color_rel.goods_id
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_color_rel.goods_id
     *
     * @param goodsId the value for car_color_rel.goods_id
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_color_rel.color_id
     *
     * @return the value of car_color_rel.color_id
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    public Integer getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_color_rel.color_id
     *
     * @param colorId the value for car_color_rel.color_id
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    public void setColorId(Integer colorId) {
        this.colorId = colorId;
    }
    private CarColor carColor;

	public CarColor getCarColor() {
		return carColor;
	}

	public void setCarColor(CarColor carColor) {
		this.carColor = carColor;
	}
    
}