package com.car.mapper.user;

import java.util.List;

import com.car.entity.user.BuyerLevel;
import com.car.entity.user.User;

public interface BuyerLevelMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_level
	 * @mbggenerated  Mon Apr 23 20:08:27 CST 2018
	 */
	int deleteByPrimaryKey(Integer levelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_level
	 * @mbggenerated  Mon Apr 23 20:08:27 CST 2018
	 */
	int insert(BuyerLevel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_level
	 * @mbggenerated  Mon Apr 23 20:08:27 CST 2018
	 */
	int insertSelective(BuyerLevel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_level
	 * @mbggenerated  Mon Apr 23 20:08:27 CST 2018
	 */
	BuyerLevel selectByPrimaryKey(Integer levelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_level
	 * @mbggenerated  Mon Apr 23 20:08:27 CST 2018
	 */
	int updateByPrimaryKeySelective(BuyerLevel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buyer_level
	 * @mbggenerated  Mon Apr 23 20:08:27 CST 2018
	 */
	int updateByPrimaryKey(BuyerLevel record);

	/**
	 * @return
	 */
	List<BuyerLevel> getAllLevels();

	BuyerLevel selectByKey(int i);
	
	BuyerLevel selectByUserLv(BuyerLevel rl);
	
	BuyerLevel selectLevel(User user);
}