package com.car.mapper.extra;

import com.car.entity.extra.Navigationbar;

public interface NavigationbarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigationbar
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    int deleteByPrimaryKey(Integer navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigationbar
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    int insert(Navigationbar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigationbar
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    int insertSelective(Navigationbar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigationbar
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    Navigationbar selectByPrimaryKey(Integer navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigationbar
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    int updateByPrimaryKeySelective(Navigationbar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigationbar
     *
     * @mbggenerated Sun Apr 15 14:42:34 CST 2018
     */
    int updateByPrimaryKey(Navigationbar record);
}