package com.car.mapper.manager;

import java.util.List;
import java.util.Map;

import com.car.entity.manager.ManagerResources;
import com.car.entity.manager.ResourcesTree;

public interface ManagerResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_resources
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    int deleteByPrimaryKey(Integer resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_resources
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    int insert(ManagerResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_resources
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    int insertSelective(ManagerResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_resources
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    ManagerResources selectByPrimaryKey(Integer resId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_resources
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    int updateByPrimaryKeySelective(ManagerResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_resources
     *
     * @mbggenerated Sun Apr 15 14:33:58 CST 2018
     */
    int updateByPrimaryKey(ManagerResources record);

	List<ResourcesTree> getResourcesTree(Integer roleId);

	void deleteResByRoleId(Integer roleId);

	void insertResourcesByRoleId(Map<String, Object> map);

	List<ManagerResources> findresbyrid(Integer roleId);

	List<ManagerResources> getManageResourcesList();

	List<ManagerResources> findPid();

}