package com.car.mapper.extra;

import java.util.List;

import com.car.entity.extra.Video;

public interface VideoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table video
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	int deleteByPrimaryKey(Integer videoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table video
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	int insert(Video record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table video
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	int insertSelective(Video record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table video
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	Video selectByPrimaryKey(Integer videoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table video
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	int updateByPrimaryKeySelective(Video record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table video
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	int updateByPrimaryKey(Video record);

	/**
	 * @return
	 */
	List<Video> getVideos();

	void videoNoChoice();

	void videoChoice(Integer videoId);

	Video findvideobychoice();
}