package com.car.entity.manager;

public class ResFunRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_function_rel.fun_id
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    private Integer funId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_function_rel.res_id
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    private Integer resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_function_rel.fun_id
     *
     * @return the value of resources_function_rel.fun_id
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    public Integer getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_function_rel.fun_id
     *
     * @param funId the value for resources_function_rel.fun_id
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    public void setFunId(Integer funId) {
        this.funId = funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_function_rel.res_id
     *
     * @return the value of resources_function_rel.res_id
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_function_rel.res_id
     *
     * @param resId the value for resources_function_rel.res_id
     *
     * @mbggenerated Sun Apr 15 14:34:53 CST 2018
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }
}