package com.car.mapper.rep;

import java.util.List;

import com.car.entity.rep.CarRepositoryRel;


public interface CarRepositoryRelMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_repository_rel
	 * @mbggenerated  Wed Apr 25 19:17:43 CST 2018
	 */
	int deleteByPrimaryKey(Integer traId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_repository_rel
	 * @mbggenerated  Wed Apr 25 19:17:43 CST 2018
	 */
	int insert(CarRepositoryRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_repository_rel
	 * @mbggenerated  Wed Apr 25 19:17:43 CST 2018
	 */
	int insertSelective(CarRepositoryRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_repository_rel
	 * @mbggenerated  Wed Apr 25 19:17:43 CST 2018
	 */
	CarRepositoryRel selectByPrimaryKey(Integer traId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_repository_rel
	 * @mbggenerated  Wed Apr 25 19:17:43 CST 2018
	 */
	int updateByPrimaryKeySelective(CarRepositoryRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_repository_rel
	 * @mbggenerated  Wed Apr 25 19:17:43 CST 2018
	 */
	int updateByPrimaryKey(CarRepositoryRel record);

	List<CarRepositoryRel> findCarRepRelList(Integer repId);

	List<CarRepositoryRel> findHistoryList();
}