package com.car.entity.extra;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_dictionary.dic_id
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    private Integer dicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_dictionary.dic_name
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    private String dicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_dictionary.dic_flag
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    private String dicFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_dictionary.dic_id
     *
     * @return the value of rep_dictionary.dic_id
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    public Integer getDicId() {
        return dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_dictionary.dic_id
     *
     * @param dicId the value for rep_dictionary.dic_id
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    public void setDicId(Integer dicId) {
        this.dicId = dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_dictionary.dic_name
     *
     * @return the value of rep_dictionary.dic_name
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_dictionary.dic_name
     *
     * @param dicName the value for rep_dictionary.dic_name
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    public void setDicName(String dicName) {
        this.dicName = dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_dictionary.dic_flag
     *
     * @return the value of rep_dictionary.dic_flag
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    public String getDicFlag() {
        return dicFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_dictionary.dic_flag
     *
     * @param dicFlag the value for rep_dictionary.dic_flag
     *
     * @mbggenerated Sun Apr 15 14:43:07 CST 2018
     */
    public void setDicFlag(String dicFlag) {
        this.dicFlag = dicFlag;
    }
}