package com.car.entity.car;

public class CarImgRel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_img_rel.car_id
	 * @mbggenerated  Fri Apr 20 13:44:02 CST 2018
	 */
	private Integer carId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_img_rel.img_id
	 * @mbggenerated  Fri Apr 20 13:44:02 CST 2018
	 */
	private Integer imgId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_img_rel.car_id
	 * @return  the value of car_img_rel.car_id
	 * @mbggenerated  Fri Apr 20 13:44:02 CST 2018
	 */
	public Integer getCarId() {
		return carId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_img_rel.car_id
	 * @param carId  the value for car_img_rel.car_id
	 * @mbggenerated  Fri Apr 20 13:44:02 CST 2018
	 */
	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_img_rel.img_id
	 * @return  the value of car_img_rel.img_id
	 * @mbggenerated  Fri Apr 20 13:44:02 CST 2018
	 */
	public Integer getImgId() {
		return imgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_img_rel.img_id
	 * @param imgId  the value for car_img_rel.img_id
	 * @mbggenerated  Fri Apr 20 13:44:02 CST 2018
	 */
	public void setImgId(Integer imgId) {
		this.imgId = imgId;
	}
}