package com.car.mapper.rep;

import java.util.List;

import com.car.entity.rep.CarRepositoryRel;
import com.car.entity.rep.Repository;

public interface RepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_repository
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    int deleteByPrimaryKey(Integer repId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_repository
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    int insert(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_repository
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    int insertSelective(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_repository
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    Repository selectByPrimaryKey(Integer repId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_repository
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    int updateByPrimaryKeySelective(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_repository
     *
     * @mbggenerated Sun Apr 15 14:30:36 CST 2018
     */
    int updateByPrimaryKey(Repository record);

	List<Repository> findRepositoryList();

	void updateStockByRepId(CarRepositoryRel carRepRel);

	void updateStockByRepId2(CarRepositoryRel carRepRel);
}