package com.car.entity.user;


import java.util.Date;

public class User {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_id
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_name
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_pwd
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.real_name
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_sex
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private Integer userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_idcard
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userIdcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_emails
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userEmails;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_tel
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_img
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_birthday
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_status
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private Integer userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_create_time
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String userCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_login_time
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private Date userLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_level_num
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private Integer userLevelNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buyer_user.user_login_num
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	private String couponName;
	private String couponMoney;
	private String couponContent;
	
	public String getCouponName() {
		return couponName;
	}

	public void setCouponName(String couponName) {
		this.couponName = couponName;
	}

	public String getCouponMoney() {
		return couponMoney;
	}

	public void setCouponMoney(String couponMoney) {
		this.couponMoney = couponMoney;
	}

	public String getCouponContent() {
		return couponContent;
	}

	public void setCouponContent(String couponContent) {
		this.couponContent = couponContent;
	}

	private Integer userLoginNum;
    private String level;

	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_id
	 * @return  the value of buyer_user.user_id
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_id
	 * @param userId  the value for buyer_user.user_id
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_name
	 * @return  the value of buyer_user.user_name
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_name
	 * @param userName  the value for buyer_user.user_name
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_pwd
	 * @return  the value of buyer_user.user_pwd
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_pwd
	 * @param userPwd  the value for buyer_user.user_pwd
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.real_name
	 * @return  the value of buyer_user.real_name
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.real_name
	 * @param realName  the value for buyer_user.real_name
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_sex
	 * @return  the value of buyer_user.user_sex
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public Integer getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_sex
	 * @param userSex  the value for buyer_user.user_sex
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserSex(Integer userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_idcard
	 * @return  the value of buyer_user.user_idcard
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserIdcard() {
		return userIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_idcard
	 * @param userIdcard  the value for buyer_user.user_idcard
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserIdcard(String userIdcard) {
		this.userIdcard = userIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_emails
	 * @return  the value of buyer_user.user_emails
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserEmails() {
		return userEmails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_emails
	 * @param userEmails  the value for buyer_user.user_emails
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserEmails(String userEmails) {
		this.userEmails = userEmails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_tel
	 * @return  the value of buyer_user.user_tel
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserTel() {
		return userTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_tel
	 * @param userTel  the value for buyer_user.user_tel
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_img
	 * @return  the value of buyer_user.user_img
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserImg() {
		return userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_img
	 * @param userImg  the value for buyer_user.user_img
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserImg(String userImg) {
		this.userImg = userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_birthday
	 * @return  the value of buyer_user.user_birthday
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserBirthday() {
		return userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_birthday
	 * @param userBirthday  the value for buyer_user.user_birthday
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserBirthday(String userBirthday) {
		this.userBirthday = userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_status
	 * @return  the value of buyer_user.user_status
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public Integer getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_status
	 * @param userStatus  the value for buyer_user.user_status
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_create_time
	 * @return  the value of buyer_user.user_create_time
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public String getUserCreateTime() {
		return userCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_create_time
	 * @param userCreateTime  the value for buyer_user.user_create_time
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserCreateTime(String userCreateTime) {
		this.userCreateTime = userCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_login_time
	 * @return  the value of buyer_user.user_login_time
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public Date getUserLoginTime() {
		return userLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_login_time
	 * @param userLoginTime  the value for buyer_user.user_login_time
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserLoginTime(Date userLoginTime) {
		this.userLoginTime = userLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_level_num
	 * @return  the value of buyer_user.user_level_num
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public Integer getUserLevelNum() {
		return userLevelNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_level_num
	 * @param userLevelNum  the value for buyer_user.user_level_num
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserLevelNum(Integer userLevelNum) {
		this.userLevelNum = userLevelNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buyer_user.user_login_num
	 * @return  the value of buyer_user.user_login_num
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public Integer getUserLoginNum() {
		return userLoginNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buyer_user.user_login_num
	 * @param userLoginNum  the value for buyer_user.user_login_num
	 * @mbggenerated  Sat Apr 21 08:49:17 CST 2018
	 */
	public void setUserLoginNum(Integer userLoginNum) {
		this.userLoginNum = userLoginNum;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", userName=" + userName + ", userPwd=" + userPwd + ", realName=" + realName
				+ ", userSex=" + userSex + ", userIdcard=" + userIdcard + ", userEmails=" + userEmails + ", userTel="
				+ userTel + ", userImg=" + userImg + ", userBirthday=" + userBirthday + ", userStatus=" + userStatus
				+ ", userCreateTime=" + userCreateTime + ", userLoginTime=" + userLoginTime + ", userLevelNum="
				+ userLevelNum + ", userLoginNum=" + userLoginNum + "]";
	}

    
}