package com.car.entity.extra;

public class Video {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.video_id
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private Integer videoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.video_url
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private String videoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.video_name
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private String videoName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.video_choice
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private Integer videoChoice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.video_time
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private String videoTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.video_price
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private Integer videoPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video.car_id
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	private Integer carId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.video_id
	 * @return  the value of video.video_id
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public Integer getVideoId() {
		return videoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.video_id
	 * @param videoId  the value for video.video_id
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.video_url
	 * @return  the value of video.video_url
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public String getVideoUrl() {
		return videoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.video_url
	 * @param videoUrl  the value for video.video_url
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.video_name
	 * @return  the value of video.video_name
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public String getVideoName() {
		return videoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.video_name
	 * @param videoName  the value for video.video_name
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setVideoName(String videoName) {
		this.videoName = videoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.video_choice
	 * @return  the value of video.video_choice
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public Integer getVideoChoice() {
		return videoChoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.video_choice
	 * @param videoChoice  the value for video.video_choice
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setVideoChoice(Integer videoChoice) {
		this.videoChoice = videoChoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.video_time
	 * @return  the value of video.video_time
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public String getVideoTime() {
		return videoTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.video_time
	 * @param videoTime  the value for video.video_time
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setVideoTime(String videoTime) {
		this.videoTime = videoTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.video_price
	 * @return  the value of video.video_price
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public Integer getVideoPrice() {
		return videoPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.video_price
	 * @param videoPrice  the value for video.video_price
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setVideoPrice(Integer videoPrice) {
		this.videoPrice = videoPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video.car_id
	 * @return  the value of video.car_id
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public Integer getCarId() {
		return carId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video.car_id
	 * @param carId  the value for video.car_id
	 * @mbggenerated  Sun Apr 22 18:42:30 CST 2018
	 */
	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Override
	public String toString() {
		return "Video [videoId=" + videoId + ", videoUrl=" + videoUrl + ", videoName=" + videoName + "]";
	}
    
}