package com.car.mapper.car;

import java.util.List;

import com.car.entity.car.CarColor;
import com.car.entity.car.CarColorRel;

public interface CarColorRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_color_rel
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    int insert(CarColorRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_color_rel
     *
     * @mbggenerated Sun Apr 15 14:25:52 CST 2018
     */
    int insertSelective(CarColorRel record);

	List<CarColorRel> findColorRelByCarId(Integer carId);

	int deleteColor(CarColorRel carColorRel);

	void deleteByColorId(Integer colorId);

	
}